module.exports={
    USER_COLLECTION:'user',
    PRODUCT_COLLECTION:'product',
    CATEGORY_COLLECTION:'category',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    ADDRESS_COLLECTION:'address',
    COUPEN_COLLECTION:'coupen',
    WALLET_COLLECTION:'wallet',
    BANNER_COLLECTION:'banner'
}